### ISSUE TITLE
Provide a way to override BUILD_JOB_NAME === context on resources.

### ISSUE THREAD

**Issue by eitah** [Pix4D/cogito#23]
Right now the resource requires that you put all tasks that affect the same job status together in the same job within a pipeline because of the choice to make github "context" ===  BUILD_JOB_NAME. For reference, I believe this is where we set it. https://github.com/Pix4D/cogito/blob/master/resource/resource.go#L213-L215

I'd like to propose allowing users to pass in an optional parameter "context" that overrides the job name  as the CONTEXT arg if not equal to "". Any objections or "gotchas" you can think of? Any reason you'd rather not have this property be configurable? 

I'm happy to PR this if you think the feature has a chance.

**Comment by marco-m-pix4d** [comment]
Hello @eitah,
I appreciate both that you took the time to look into the code and that you opened this ticket instead of jumping to a PR.
I am trying to understand better the use case. I see what you want to do, I would like to understand the why.

To make a concrete example, I think that you would like to be able to have a pipeline with, say, 2 jobs as follows:

* `jobA`, containing among the others, task `tA`.
* `jobB`, containing among the others, task `tB`.

Where for some reasons tasks `tA` and `tB` are related, and you would like that `jobB` set the GH status with a `context` that is different from the name `jobB`.

The question I have is this: if you already have the two jobs, it means that they have a certain logical grouping. So, you could push GH status two times, the first time on completion of `jobA`, and the second time on completion of `jobB`. If the names `jobA` and `jobB` are meaningful, they work well as GH context.

For example, if first job is `build` and second job is `test`, the same commit would be decorated with contexts `build` and `test`. This would also give more granularity.

What am I missing?

**Comment by eitah** [comment]
I really like and agree with that point about mandating each job pipeline close its own statuses as a way to enforce granularity. I'll pitch that to the Dev that first raised the bug. Without hearing from him I'd assume his objection might be:

- More YAML to configure the job closure step per pipeline. 
- The code change to enable an override of the job name === context is relatively slight (1-3 lines?) which is nothing in go terms.

Thanks!
Eli

**Comment by eitah** [comment]
He's good with just having each job manage its own statuses so I think this feature is not required. No code == good code :) thanks again!

**Comment by eitah** [comment]
Update after a week of closing statuses per pipeline:

> i really don’t like that cogito resource =\

>they make it so complicated to just 1) when the pipeline starts, mark a commit/PR pending; 2) anywhere along the way, if something fails, mark it failed; 3) at the very end, mark it a success

>instead you have to have 1 status per job, so the PR ends up flowing through: pending/job-a (yellow dot showing); success/job-a (green check mark showing); 10 seconds later, pending/job-b (back to the yellow dot!); success/job-b (green…); pending/job-c (hello again yellow dot); failed/job-c (red! all those previous greens were lies hope you didn’t click merge at the wrong time)

**Comment by marco-m-pix4d** [comment]
I can understand that it could cause confusion, but I have the impression that the real cause is that the developer is not familiar with how GitHub works.

All CI/CD systems giving feedback on GitHub work in this way. I make two examples:

1. directly on a commit (what the developer is referring to). It is enough to click on the icon to get a popup with the details:
![cogito](https://user-images.githubusercontent.com/51477941/102636200-a36fbf00-4154-11eb-8578-6d7e2b236c22.png)
You can test this in the cogito test repo: https://github.com/Pix4D/cogito-test-read-write

2. All the details are given also in a PR, for example: 
![pr](https://user-images.githubusercontent.com/51477941/102636507-03fefc00-4155-11eb-9c2f-5981bee4b53f.png)

In both cases, details would go away with an explicit `context`...

**Comment by eitah** [comment]
let's use a hypothetical pipeline `my-pipeline` with three job pipelines
1. build
2. test
3. release

what you're proposing would involve three discrete `detail` sections in the github ui with headers named `build` `test` `release`. 

What he'd like is the ability to have a single context `my-pipeline` that all three jobs would post to as they are executed serially, and the detail section would give information ("build 2" in your example above) could be used to print information about what exactly was pending, or the user could click into the job itself and see it. 

Does that clarify?

**Comment by eitah** [comment]
Just following up on this. I realize with the holiday it might not be the easiest time to consider new feature PRs on this repo.

**Comment by marco-m-pix4d** [comment]
I thought a bit more about this. Although I am still not convinced by this specific use case, I realized that in general having the capability of setting a custom context could be useful, so I am open to reviewing a PR.

As discussed before, setting the context should be optional. Please also consider how to test this new feature.

Regarding the holidays, yes, you might want to come back to this at the beginning of the next year.

**Comment by marco-m-pix4d** [comment]
See also #24 and #25.

**Comment by marco-m-pix4d** [comment]
This will be closed by #34.
